### PR TITLE
Decompose main module

### PR DESCRIPTION
**Pull request by tronin**
Decomposition of the selector is necessary for further work with it. For example, in the future we will be able to rewrite some render functions into components and allow them to be passed through props.

### CODE REVIEW

**Comment by tronin** [comment]
I don't know what's happens
```react-native-picker-select git:(feature/decompose) codeclimate validate-config
No errors or warnings found in .codeclimate.yml.```

**Comment by lfkwtz** [comment]
Not inherently against this idea, but can you add examples and tests to show off the benefits?

**Comment by tronin** [comment]
1. Decomposition makes your code more readable, right now it's too difficult to understand that's really happens inside
2. Memoization prevents the creation of a function instance, if such an instance has already been created at the previous step and the arguments are identical 
3. My pullrequest will help to further implement flow/typescript or to cover some parts of the code that are difficult to cover with tests at the moment.

**Comment by lfkwtz** [comment]
Sorry, I meant actual code examples showing the benefits you mentioned when you opened the PR

**Comment by tronin** [comment]
https://github.com/lawnstarter/react-native-picker-select/commit/ed87ab6f7e32d7f71c938e8e75dc5068a4f439ac

Mate :-) come on

**Comment by lfkwtz** [comment]
I’d opened a pr for that before this exited #122. Still interested in this pr - just waiting on your response.

**Pull request closed without merging**
