### PR TITLE
iOS refactor onDone press callback handler

### PR DESCRIPTION
**Pull request by jgrocott**

### CODE REVIEW

**Comment by jgrocott** [comment]
@lfkwtz I think i've located the issue and it seems to be isolated to iOS only. On a physical iOS device, the Modal seems to prevent the callback working correctly when using the onDonePress callback. In my case the callback was fired however the views that it was attempting to present the user would fail. Another scenario is when attempting to push a new screen onto the stack (react-native-navigation). It would fire but never actually navigate the user. I had setTime in my code to pause for 1sec and that was the only way to consistently achieve the desired results. 

In this update, I have set the Modal callback 'onDismiss' to fire the 'onDonePress' callback instead. Without this, my callback is fired before the Modal has closed and I get unexpected results.

I'll fix the above test issues :) Apologies again for the duplicate PR.

**Comment by lfkwtz** [comment]
This looks pretty good - just clarifying is this done or are you still planning to add something else to it?

**Comment by jgrocott** [comment]
@lfkwtz Apologies for the delay. I'm all done :)

**Comment by lfkwtz** [comment]
@jgrocott this caused some regressions -- can you check this beta for me:
 https://www.npmjs.com/package/react-native-picker-select/v/7.0.0-beta.0

trying to fix the regressions without undoing the work you did

**Comment by jgrocott** [comment]
Sure thing. Leave it with me, I should have some time over the new few days to check it out

**Comment by lfkwtz** [comment]
@jgrocott  -  any chance to check it out yet?

**Comment by jgrocott** [comment]
@lfkwtz Sorry, i dropped the ball on this one. Got busy and distracted - it's that time of year! 

OK so i've finally had time to test this and can see the concerns from others with regards to the modal onDismiss issue. Unfortunately 7.0.0-beta breaks for me. The issue remains and is related to the onDonePress callback firing before the modal has closed. This prevents any additional view renders or transitions occurring because it's blocked by the modal (still) closing. This seems to be perfectly fine in the iOS simulator which for me has always been quite forgiving. Running on a physical device however is where the issue is present.

For now, i'll continue to run our app(s) off of my fork of your repo. The modal onDismiss workaround isn't an issue for us at present and I don't really have time to find a solution.

**Comment by lfkwtz** [comment]
Thanks so much for checking it out - I had a feeling it may have reversed what you had worked on. I’ll look into it.

**Comment by lfkwtz** [comment]
Would love to circle back on this and look into it further, but for now I'm going to revert the regression. Thanks again for your help.

**Pull request merged**
