### PR TITLE
 Fix appearing selectedValue text over next view

### PR DESCRIPTION
**Pull request by natsuki-yamanaka**
## Issue
#83

### CODE REVIEW

**Comment by natsuki-yamanaka** [comment]
I think it's OK.
I confirmed on RN 0.56.0 on my repository sample https://github.com/natsuki-yamanaka/ReactNativePickerSelectSample , and works well.

**Comment by lfkwtz** [comment]
Thanks. I assumed it’d be fine - appreciate you checking.

**Comment by ManigandanRaamanathan** [comment]
Still not working. I'm still getting the text below view. I'm using version. 5.2.0

**Comment by lfkwtz** [comment]
@ManigandanRaamanathan mind filling out a new bug report?

**Pull request merged**
