### PR TITLE
fix: font visibility Issue on android emulator (#531)

### LINKED ISSUE #531: Picker item list not displaying items on Android
**Describe the bug**<br />
For some reason, when using the Android emulator, the picker item list is not showing the item text. The item text is _there_, I think... but it's not visible. I am not 100% sure, but I think it's a simple styling issue. I can't quite figure out why/where/how the item text is getting set to make it not appear, and I can't debug it with the item inspector because it keeps disappearing when I try to turn on the item inspector.

**I have a possible work around**, but I would like to see this added to the main source so I don't have to rely on a local copy to do it. That is to add the item.style to the Picker.Item properties. That way we can pass in the styles for the items to use.

**To Reproduce**<br />

1. Umm... make a picker for android
2. Fire up the emulator
3. see the screen shot for what I mean.

**Expected behavior**<br />
I expect the item text to be visible.

**Screenshots**<br />
Without Styles:
image

With styles and fontsize set to 20:
image

**Additional details**<br />
-   Device: Android emulator 32.1.15.0
-   OS: Android 33
-   react-native-picker-select version: 9.0.0
-   react-native version: latest
-   expo sdk version: latest

**Reproduction and/or code sample**<br />
```
                <Picker.Item
                    label={item.label}
                    value={item.value}
                    key={item.key || item.label}
                    color={item.color || defaultItemColor}
                    testID={item.testID}
                    style={item.style}  // <---- THIS IS WHAT I ADDED SO IT WILL WORK
                />
```
Then in my code:
```
      items={
       {
          label: BookingEventCategoryDisplay.getBookingEventCategory(value),
          value,
          color: "#000000",
          key: value.toString(),
          style: { fontSize: 20 },   //  <----- Added this to make the items appear visible.
       } ,
      ....
```

### PR DESCRIPTION
**Pull request by atif089**
Fixes #531 

| Before  | After |
| ------------- | ------------- |
| image | image
  |

### CODE REVIEW

**Review by ElisabethCardella — APPROVED** [review]
I came across this issue (https://github.com/lawnstarter/react-native-picker-select/issues/531) and I confirm that this code change fixes it 👌

**Comment by atif089** [comment]
Hi @lfkwtz ,

Silly question, is this released? I see a merge into master, but I'm unable to narrow it down to a specific release version. Asking because I'm using my personal fork for a project, and I'd love to go back to a proper release instead.

Thanks

**Comment by lfkwtz** [comment]
> Hi @lfkwtz ,
> 
> Silly question, is this released? I see a merge into master, but I'm unable to narrow it down to a specific release version. Asking because I'm using my personal fork for a project, and I'd love to go back to a proper release instead.
> 
> Thanks

nope the pr is still open. there's a merge conflict you'll need to fix.

**Comment by atif089** [comment]
I don't run into this issue any more after upgrading to `v9.1.3` so I'm closing this.

**Pull request closed without merging**
