### PR TITLE
Added scrollLabel prop

### PR DESCRIPTION
**Pull request by cmcaboy**
I had a requirement from a client in which the label displayed in the picker was different than the label displayed in the actual select field. As a result, I added another optional property to Item called "scrollLabel". If it is truthy, its value is used in place of label in the native picker. Label is still used to show the actual selected element.

In this example below, label is "AU +61" while scrollLabel is "Australia +61".

image

### CODE REVIEW

**Comment by lfkwtz** [comment]
thinking of a way we can do this with maybe one or two params that will cover all possible needs in the future. typing this while i think out loud. `displayValue` is currently a bool that will show the value instead of the label in the input.

what if this concept supplanted that - and we had one param called `pickerLabel` that takes a string.

if a user only sets `label`, it applies to both the picker and the input - current default.

if a user sets `label` and `pickerLabel`, it applies the `label` to the input, and the `pickerLabel` to the picker.

at that point, you could display whatever you want to users. i think that'd cover it all. other option would be to call it `inputLabel` and effectively do the reverse logic. i think that may be a bit more self explanatory - thoughts?

**Comment by cmcaboy** [comment]
@lfkwtz I like that approach!

I can change my PR to reflect that requirement, but it may be a bit before I can get to it. Maybe a week or 2.

**Comment by lfkwtz** [comment]
@cmcaboy still going to tackle this?

**Comment by cmcaboy** [comment]
@lfkwtz Yes, I still plan to tackle this. Give me another week or so. My schedule is starting to open up.

**Comment by lfkwtz** [comment]
had a bit of free time so took on this change. closing this one out.

**Pull request closed without merging**
