### PR TITLE
onOpen & onClose functionality added

### PR DESCRIPTION
**Pull request by OllySturrock**
Added the ability to run a function when/before the picker loads.
The need to scroll to a input & hide another custom input when the picker is selected is the use case that made me contribute.

### CODE REVIEW

**Comment by OllySturrock** [comment]
The failed check's reasoning is "Function togglePicker has a Cognitive Complexity of 10 (exceeds 5 allowed). Consider refactoring."
The code looks readable to a human from my perspective but if there is a different way you would want this feature to be implemented, comment back and I can sort it out.

**Comment by robwalkerco** [comment]
This is great 👏. I wouldn't be able to use this package without this functionality, as I need to animate 'floating labels' based on the active state of the input, as whether it has a value selected or not.

I hope it gets merged so I don't need to continue to use this PR branch.

**Comment by robwalkerco** [comment]
@OllySturrock Please can you also update the `index.d.ts` file to add

```
onOpen?: () => void;
onClose?: () => void;
```

**Comment by lfkwtz** [comment]
Thanks @OllySturrock for the PR, but #126 was done a little cleaner and with tests.

**Pull request closed without merging**
