### PR TITLE
Migrated to Community Picker

### PR DESCRIPTION
**Pull request by mowme**
react-native core picker is being deprecated and moved to @react-native-community/picker.

Added to dev dependencies and index.js + updated package version.

### CODE REVIEW

**Comment by lfkwtz** [comment]
#283

**Comment by lfkwtz** [comment]
I agree this is the future for this library - but there’s no compelling reason to switch now. Official docs still don’t mention deprecation.

**Comment by unfrgivn** [comment]
@lfkwtz https://reactnative.dev/docs/picker

**Comment by unfrgivn** [comment]
Apologies, I only saw the 2 closed PRs, I just read https://github.com/lawnstarter/react-native-picker-select/pull/303

**Pull request closed without merging**
