### PR TITLE
Fix the shot from a press anywhere on the screen

### PR DESCRIPTION
**Pull request by andercard**
It solved small error that when pressing in some parts of the screen opens the modal in android

### CODE REVIEW

**Comment by lfkwtz** [comment]
Thanks I'll take a look

**Comment by lfkwtz** [comment]
Looks like it renders a second Picker element. See https://snack.expo.io/SJSkBXNWE

**Comment by andercard** [comment]
adding a zero opacity is solved

image

**Comment by lfkwtz** [comment]
Looks good. Going to check it out on a couple different Android devices and then I'll merge it in.

**Pull request merged**
