### PR TITLE
Fix Icon prop type

### PR DESCRIPTION
**Pull request by noterB**
#478

### CODE REVIEW

**Comment by LouisKraemer** [comment]
Do we have an ETA on a new release containing this work?

**Review by lucasoliveiraw00 — APPROVED** [review]

**Comment by lucasoliveiraMM** [comment]
Hello, is there an estimate on when this pull request will be released in a version?

**Comment by lucasoliveiraw00** [comment]
Hello, is there an estimate on when this pull request will be released in a version?

**Comment by lucasoliveiraw00** [comment]
@lfkwtz

**Comment by lucasoliveiraw00** [comment]
> Hello, is there an estimate on when this pull request will be released in a version?

@lfkwtz

**Review by pelivan — APPROVED** [review]

**Comment by pelivan** [comment]
I found a great workaround.

It is possible to create helper file, in my case i called it iconHelper.tsx and create a function that will return JSX like this

```
export const getPickerIcon = () => {
  return <ChevronDownIcon />;
};

```
After that you can import it to component where picker is used and use it like 

```
   <RNPickerSelect
                    Icon={getPickerIcon}
```

**Review by lfkwtz — APPROVED** [review]

**Pull request merged**
