### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lekterable**
readme incorrectly describes `InputAccessoryView` as a boolean when in fact it expects a function
Zrzut ekranu 2020-03-30 o 01 28 47

### CODE REVIEW

**Comment by lfkwtz** [comment]
`Component` would be more appropriate

**Comment by lekterable** [comment]
@lfkwtz not necessarily, because the function can also return null if we don't want to render anything, correct?

**Comment by lfkwtz** [comment]
sure - but you could also render a fragment to achieve the same thing. or an empty view. either way, compared to the rest of the props that are specifically functions - it's not really the same. Icon is already listed as a component.

the docs could use a lot of work - hard to convey everything in the single readme well.

**Comment by lfkwtz** [comment]
did you want to make that change?

**Pull request closed without merging**
