### PR TITLE
Multiple picker wheels

### PR DESCRIPTION
**Pull request by ajp8164**
Allows calling component to specify multiple parallel pickers (wheels) for choosing a set of values. Changes are backward compatible. When specifying multiple pickers the calling component manages items as an array of arrays with the outer array representing the target picker. The caller receives the overall value as an array of values, one entry for each parallel picker. If a single picker is specified then the caller manages simple objects for items (a non nested array) and values. The caller can specify the width of each picker for the UI; default width is (100% / num pickers). Placeholders can be specified per picker.

### CODE REVIEW

**Comment by ajp8164** [comment]
Added capability to add labels to each of the specified picker wheels. For example, add hours min and sec to a timer picker with 3 wheels.

**Comment by grousseva** [comment]
When will this be added??? Its a great feature!!!

**Comment by ajp8164** [comment]
I'm still using my fork. Would like to have this merged if possible.

**Comment by lfkwtz** [comment]
thanks for the contribution here andy but this component is going to be in maintenance mode for the foreseeable future so i don't think adding new functionality of this type is the best path forward for the health of the codebase. if you'd like to make a fork of the project with this added feature we could link out to it in the readme.

**Pull request closed without merging**
