### PR TITLE
Add support to caption

### LINKED ISSUE #164: Add support to caption
**Is your feature request related to a problem? Please describe.**
No. The layout I'm developing defines a picker with a caption that looks like a [InputAccessoryView](https://facebook.github.io/react-native/docs/inputaccessoryview)

**Describe the solution you'd like**
A prop like `caption` in order to render a custom text between the arrows and the done button.

**Describe alternatives you've considered**
I didn't find any a better alternative than add this prop.

**Additional context**
image

### PR DESCRIPTION
**Pull request by helielson**
closes #164

image

### CODE REVIEW

**Comment by KoAi** [comment]
This works well, could it be merged ?

**Comment by jrapala** [comment]
Hey @helielson, can you update the README and the TypeScript file as well? Happy to add a commit to your fork if you add me as a collaborator...

**Comment by lfkwtz** [comment]
If you have suggestions on how we can combine this and #160 together - i'm open to it

**Comment by helielson** [comment]
@jrapala @lfkwtz @KoAi I'm closing this PR in favor of #188

**Pull request closed without merging**
