### PR TITLE
Update iOS design in styles.js

### LINKED ISSUE #280: Update iOS design to fit native look and feel
Currently the iOS design looks a bit outdated due to changes in the past years. May I provide a PR for it?

New colors are hand-picked using ColorSnapper and sizes using PixelWinch - directly from native components on newer iOS versions (ie. 12 and 13).

### PR DESCRIPTION
**Pull request by winkelsdorf**
Closes #280

### CODE REVIEW

**Comment by lfkwtz** [comment]
mind providing screenshot comparisons in the pr?

**Comment by winkelsdorf** [comment]
Sure, sorry that I skipped that part (honestly I was lazy as the changes are subtile except for the font).

## react-native-picker-select
Screen Shot 2020-02-13 at 23 47 53

## iOS
Screen Shot 2020-02-13 at 22 42 53

## This PR
Screen Shot 2020-02-13 at 22 42 46

**Comment by lfkwtz** [comment]
this is what i'm seeing on iOS 13.3

IMG_3743

**Comment by winkelsdorf** [comment]
@lfkwtz Thanks for double checking!

The bottom background color of my change is correct, verified again with a color picker in the iOS simulator.

I will check the upper part with the chevrons again.

**Comment by winkelsdorf** [comment]
Update: Still investigating.

I currently don't know where the black textcolor of RN's iOS InputAccessoryView "Done" button comes from.

I think I am still right about:
- Size of the "Done" button text
- Right padding for "Done" button
- Height (45px instead of 44px as separator is counted within here), color of separator for modalViewMiddle and separator linewidth (1px instead of 0.5)
- Chevron color
- Background color of modalViewBottom (blueish tint was changed with iirc iOS 9 into a more grayish look)

**Comment by lfkwtz** [comment]
https://imgur.com/a/z8bx2H3

I’m seeing blue chevrons

**Comment by winkelsdorf** [comment]
@lfkwtz Oh sure, so basically everything except the InputAccessoryView text/button tint is correct in this PR. Thanks for checking!

For testing purposes I completely removed the button color but still see black text. I am now comparing native iOS side (Xcode) with the RN part to see where it comes from.

**Comment by winkelsdorf** [comment]
Ah it looks like if no color is given the react native buttons used default to black (#000000). Of course iOS normally defaults to `systemBlueColor` which is `#007AFF`:

Screen Shot 2020-02-15 at 16 42 24
Screen Shot 2020-02-15 at 16 42 38

So you were right about the chevron and text colors and I was wrong. Sorry for that!

Going to update the PR now.

**Comment by winkelsdorf** [comment]
Thanks for merging! 🎉

**Pull request merged**
