### PR TITLE
On open/close functions

### PR DESCRIPTION
**Pull request by robwalkerco**
I'm creating this PR as I'm using the PR branch at #115 but without an updated type definition, its causing annoying warnings.

I'm also hoping to bring the Cognitive Complexity down below 5 so that the tests pass :)

I've also updated the tests to test these two new props

### CODE REVIEW

**Comment by harrydema** [comment]
+1

**Comment by lfkwtz** [comment]
closes #115

**Comment by DriesVS** [comment]
Whats the status on this? It also looks like #115 has the same functionality.

**Comment by robwalkerco** [comment]
Yeah @DriesVS, it’s based on #115, but included updated types, new tests, and passed all the existing build tests.

I only created it as I was fed up with the typescript errors!

**Comment by DriesVS** [comment]
Looks like everything is working. This can get merged, @LawnStarterTeam

**Pull request merged**
