### PR TITLE
Add support for iOS dark mode

### PR DESCRIPTION
**Pull request by sarcadass**
I added a new prop `darkTheme` to have a dark theme on the picker (only on **iOS**). I used the same color as the native iOS picker in dark system theme when you open a `<select>` on the web. I wrote a test with the feature.

### Picture
dark-theme-ios

### Video
https://user-images.githubusercontent.com/2452603/138324017-8165abd9-2841-4653-8636-5b847eebc8cf.mp4

## Test the feature
1. Download the [codeSandbox repo](https://codesandbox.io/s/react-native-picker-select-dark-theme-00t78). I could not make a snack because I use the `Appearance` API of `react-native` in the example. To use `Appearance`, [you need to edit the **App.json** if you use expo](https://docs.expo.dev/versions/latest/sdk/appearance/), a thing you can't do in a snack. I provided the App.json file in the codeSandbox repo.
2. `npm i && expo start`
3. Open the App with expo and open the picker, change your system theme on iOS then switch back to the App and open the picker again.

## Related issue
#245

### CODE REVIEW

**Comment by cvburgess** [comment]
@lfkwtz is there anything i can do to help get this merged in?

**Comment by sarcadass** [comment]
I just made a fix to apply the proper custom styles for the light & dark themes.

**Comment by luizaugustoventura** [comment]
> @lfkwtz is there anything i can do to help get this merged in?

You guys have any update on this PR? This would be a really important one for me and the project I'm working 😊️

**Review by LFMAKER — APPROVED** [review]

**Comment by LFMAKER** [comment]
@lawnstarter

**Comment by felri** [comment]
Any updates?

**Comment by Zzzhuk** [comment]
@lawnstarter

**Comment by LFMAKER** [comment]
Any updates?
Has this repository been abandoned?

**Review by MauriceNino — APPROVED** [review]

**Comment by tomassvatek** [comment]
Why the PR has not been merged?

**Review by octagonalsquare — APPROVED** [review]
Looks great to me! And its a very much needed feature.

**Review by tomassvatek — APPROVED** [review]

**Comment by stevenvz** [comment]
@lawnstarter this PR has multiple approvals & would be very helpful, please merge or provide an update if you can. Thanks! :)

**Comment by stevenvz** [comment]
Or is @LawnStarterTeam the correct @? ^

**Comment by sophie-li** [comment]
+ 1

**Comment by sophie-li** [comment]
Any updates on this, please? @LawnStarterTeam

**Comment by LFMAKER** [comment]
Any updates on this, please? @LawnStarterTeam

**Comment by LFMAKER** [comment]
Any updates? I think it's time to start a fork of this project and fix all these problems.

**Review by MaciejMajchrzak — APPROVED** [review]
LGTM!

**Review by awibox — APPROVED** [review]

**Review by diidiiman — APPROVED** [review]

**Comment by awibox** [comment]
use `npm install react-native-picker-select-updated` to get dark mode

**Review by lfkwtz — APPROVED** [review]

**Pull request merged**
