### PR TITLE
fix warning of TouchableWithoutFeedback does not work well with Text children. Wrap children in a View instead.

### PR DESCRIPTION
**Pull request by ferretdayo**
Thank you for created great library of `react-native-picker-select`.
I fixed follow warning!
please check this pr.
thank you

## versions
- React Native: 0.56.0
- react-native-picker-select: 5.0.0

## problem
image

## code

```
<RNPickerSelect
    items={itemList}
    placeholder={{}}
    onValueChange={(value) => changeValue(value)}
    value={item}
>
    <Button>
           Select
     </Button>
</RNPickerSelect>
```

### CODE REVIEW

**Comment by lfkwtz** [comment]
Thanks. Looks like I accidentally removed that in v5 cleanup. Can you add a prop of ‘testID=“needed_for_touchable”’ to the View’

**Comment by ferretdayo** [comment]
ok!
just a moment :)

**Comment by RodrigoWP** [comment]
Hi!, Will you release a new version with this?
Tks :)

**Comment by lfkwtz** [comment]
done

**Comment by RodrigoWP** [comment]
It's works fine. Great job 👍

**Comment by ferretdayo** [comment]
great job!

**Pull request merged**
