### PR TITLE
allow chevron style changes

### PR DESCRIPTION
**Pull request by lfkwtz**

### CODE REVIEW

**Comment by jacek213** [comment]
@lfkwtz would be nice to document on how to put a custom component as a chevron

**Comment by lfkwtz** [comment]
@jacek213 curious -- how 'custom' of a component are you trying to use?

**Comment by jacek213** [comment]
@lfkwtz Thanks for a quick reply! Well, I just need a chevron, the one looking like this:

image

**Comment by lfkwtz** [comment]
this pr specifically opened up the ability to modify the up/down chevrons on the 'done bar' in the modal --- is that what you're trying to modify?

**Comment by jacek213** [comment]
Not sure I know what a done bar is exactly. I need to modify the chevron on the picker itself to make it look like this on both platforms:

image

**Comment by lfkwtz** [comment]
Not difficult - can be done with pure css - use the chevron css at the bottom of the source as a reference.

FWIW #143 will make this a bit easier - planning to release in the next few days

**Comment by jacek213** [comment]
@lfkwtz thanks a lot for advice, the following css passed as `icon` styles was what I needed:




    top: 10,
    width: 12,
    height: 12,
    backgroundColor: 'transparent',
    borderTopWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 1,
    borderRightColor: 'red',
    borderLeftColor: 'transparent',
    borderTopColor: 'red',
    transform: [{ translateY: 8 }, { rotate: '135deg' }],

**Comment by lfkwtz** [comment]
you can probably kill the `translateY` and just use `top` (or vice-versa)

**Pull request merged**
